### ISSUE TITLE
Error in schematic

### ISSUE THREAD

**Issue by casainho** [KingQueenWong/bmsbattery_s06s_controller_hardware#1]
Original message: https://endless-sphere.com/forums/viewtopic.php?f=30&t=87870&p=1325371#p1325352

I've discovered a triple error in the S06C schematic.

+ of C1 is conected to cathode of D2, + of C3 is conected to cathode of D4, + of C14 is conected to cathode of D8, and not to Vout.
Otherwise the boostrap will not work :!:

Hope it may help in case of troubleshooting.

**Comment by KingQueenWong** [comment]
I fixed it

**Comment by casainho** [comment]
Great!! Thank you.
